ci: update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,8 +22,8 @@ jobs:
             CONFIG_BRANCH=$(echo "$CONTENT" | jq -r '.config.branch')
             echo "Path: $CONFIG_PATH"
             echo "Branch: $CONFIG_BRANCH"
-            JSON_FILE_URL="https://raw.githubusercontent.com/$CONFIG_PATH/$CONFIG_BRANCH/schema.json"
-            curl -sS "$JSON_FILE_URL" > temp.json
+            echo "URL del archivo schema.json: $JSON_FILE_URL"
+            curl -sS "$JSON_FILE_URL" > temp.json || { echo "Error al descargar schema.json"; exit 1; }
 
       - uses: InoUno/yaml-ls-check@develop
         with:
