fix: update setup config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,7 +30,7 @@ jobs:
             echo "Branch: $CONFIG_BRANCH"
             JSON_FILE_URL="https://raw.githubusercontent.com/$CONFIG_PATH/$CONFIG_BRANCH/schema.json"
             echo "URL del archivo schema.json: $JSON_FILE_URL"
-            curl -sS "$JSON_FILE_URL" > Setup/temp.json || { echo "Error al descargar schema.json"; exit 1; }
+            curl -sS "$JSON_FILE_URL" > temp.json || { echo "Error al descargar schema.json"; exit 1; }
 
       - uses: InoUno/yaml-ls-check@develop
         with:
